"""The interface the rest of irisfs uses; implemented by AtelierClient and the test fake."""

from __future__ import annotations

from typing import Protocol

from irisfs.atelier.models import DocInfo, ImportResult, NamespaceInfo, ServerInfo


class AtelierApi(Protocol):
    def server_info(self, *, refresh: bool = False) -> ServerInfo: ...
    def namespaces(self) -> list[str]: ...
    def namespace_info(self, ns: str) -> NamespaceInfo: ...
    def list_docs(self, ns: str, *, category: str = "*", generated: bool = False) -> list[DocInfo]: ...
    def doc_timestamp(self, ns: str, name: str) -> str: ...
    def export_xml(self, ns: str, name: str) -> bytes: ...
    def import_xml(
        self, ns: str, data: bytes, *, file: str = "irisfs.xml", flags: str = "ck"
    ) -> ImportResult: ...
    def delete_doc(self, ns: str, name: str) -> None: ...
    def close(self) -> None: ...
